2019/03/06 08:01:04 [error] 743#0: *2 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/sql.php?server=1&db=ddtest&table=test_transaction&pos=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/06 08:02:16 [error] 743#0: *5 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/sql.php?server=1&db=ddtest&table=test_transaction&pos=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/06 08:02:17 [error] 743#0: *5 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/sql.php?server=1&db=ddtest&table=test_transaction&pos=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/06 08:02:18 [error] 743#0: *5 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/sql.php?server=1&db=ddtest&table=test_transaction&pos=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/06 08:02:18 [error] 743#0: *5 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/sql.php?server=1&db=ddtest&table=test_transaction&pos=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/06 08:02:19 [error] 743#0: *5 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/sql.php?server=1&db=ddtest&table=test_transaction&pos=0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/07 09:41:01 [error] 747#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /phpmyadmin/index.php?db=ddtest&table=test_transaction&target=sql.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/07 11:22:22 [crit] 747#0: *62 open() "/usr/local/var/run/nginx/client_body_temp/0000000001" failed (13: Permission denied), client: 127.0.0.1, server: ddyiiyii.com, request: "POST /phpmyadmin/tbl_replace.php HTTP/1.1", host: "ddyiiyii.com"
2019/03/07 11:22:57 [crit] 747#0: *63 open() "/usr/local/var/run/nginx/client_body_temp/0000000002" failed (13: Permission denied), client: 127.0.0.1, server: ddyiiyii.com, request: "POST /phpmyadmin/tbl_replace.php HTTP/1.1", host: "ddyiiyii.com"
2019/03/11 08:32:49 [error] 675#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/12 10:10:27 [error] 675#0: *21 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 273. in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\web\HeadersAlreadySentException))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\web\HeadersAlreadySentException))
#4 {main}
Previous exception:
yii\web\HeadersAlreadySentException: Headers already sent in /Users/wy/M" while reading upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/info HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:38:30 [error] 675#0: *312 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:39:20 [error] 675#0: *312 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:43:14 [error] 675#0: *320 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:46:07 [error] 675#0: *326 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:46:08 [error] 675#0: *326 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:46:10 [error] 675#0: *326 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 09:46:20 [error] 675#0: *326 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare1() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 423" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
2019/03/13 10:03:42 [error] 675#0: *351 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare app\controllers\TestController::actionPdoPrepare2() in /Users/wy/MySource/project/githubProject/PHP/ddyiiyii/basic/controllers/TestController.php on line 479" while reading response header from upstream, client: 127.0.0.1, server: ddyiiyii.com, request: "GET /index.php?r=test/pdo-prepare3 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "ddyiiyii.com"
